### ISSUE TITLE
InvalidOperationException when using ObjectId in an action

### ISSUE THREAD

**Issue by yaseralnajjar** [BlueshiftSoftware/EntityFrameworkCore#10]
In the same project attached in the previous issue, this works fine (using string as a parameter):

**OwnerController** 

```
public class OwnerController : Controller
{
    public async Task<IActionResult> Add(string id)
    {
        //var objectId = new ObjectId(id); // this is the workaround way
    }
}
```

But when I change it into this:
```
public async Task<IActionResult> Add(ObjectId id)
```

It causes this exception:
```
InvalidOperationException: Could not create an instance of type 'MongoDB.Bson.ObjectId'. Model bound complex types must not be abstract or value types and must have a parameterless constructor.
```

The weird part is that in the **CarsController**, this works fine:
```
public async Task<IActionResult> Edit(ObjectId id)
{
    var car = await _context.Car.SingleOrDefaultAsync(m => m.Id == id);
    if (car == null)
    {
        return NotFound();
    }
    return View(car);
}
```

**Comment by crhairr** [comment]
This is not a bug in the MongoDb provider, this is a missing model binder with ASP.NET Core. You need to create a custom `JsonConverter` for `ObjectId` and register it with:

```C#
services
    .AddMvc()
    .AddJsonOptions(options => options.SerializerSettings.Converters.Add(new MongoDbObjectIdConverter()));
```

The guys over at MongoDB really should have created an official `ObjectIdJsonConverter` and shipped with the official C# driver, but hey... nobody's perfect.

Since this is a general ASP.NET Core problem, it is outside the scope of EF Core itself and outside the scope of this repository. I probably will not add a `MongoDbObjectIdJsonConverter` to the MongoDb provider library directly, but I will consider adding a compatibility library to bridge functionality gaps like this.

It will take me a while to get around to that (if I do it), so in the meantime I suggest you implement your own simple `JsonConverter`. There's an [ObjectIdTypeConverter](https://github.com/crhairr/EntityFrameworkCore.MongoDb/blob/3e1b6571d1706190e8fe7162662143e3059d1d0d/src/Blueshift.EntityFrameworkCore.MongoDB/ObjectIdTypeConverter.cs) in the MongoDb provider library that you can wrap for simplicity.
