### ISSUE TITLE
Navigating to a foreign document doesn't load any of it's data, only the Id field is populated

### ISSUE THREAD

**Issue by LoghamLogan** [BlueshiftSoftware/EntityFrameworkCore#17]
Hey, when I navigate to a document via a virtual property I would normally expect EF to lazy load the entity (with everything populated). When I try this with MongoDb it returns an empty entity with just the Id field populated.

I would have thought it should load the entire document to avoid having to write an additional query every time I want to fetch the data. In my mind that's the whole point of the virtual property (otherwise I'd just store the Id field).

Thoughts? Am I doing it wrong?
Cheers.

Example:
```
public class AccountData
{
    public Guid Id { get; set; }
    public string Username { get; set; } = string.Empty;
    public ICollection<UserItem> EmbededList { get; set; }
}

public class UserItem
{
    public string Name { get; set; }
    public int Foo { get; set; }
    public bool Bar { get; set; }
}

public class CharacterData
{
    public Guid Id { get; set; }
    public string Name { get; set; }

    // Navigation to account document
    public virtual AccountData Account { get; set; }
}

static void Main(string[] args)
{
`Console.WriteLine("Running...");
    try
    {
        using (var context = new FooContext())
        {
            var account = context.Accounts.Add(new AccountData()
            {
                Username = "acc" + new Random().Next(Int32.MaxValue),
                EmbededList = new List<UserItem>()
                {
                    new UserItem() {Name = "asd", Bar = true, Foo = 1001},
                    new UserItem() {Name = "asd2", Bar = false, Foo = 1002},
                    new UserItem() {Name = "asd3", Bar = true, Foo = 1003},
                }
            });

            context.Characters.Add(new CharacterData()
            {
                Name = "char" + new Random().Next(Int32.MaxValue),
                Account = account.Entity,
            });

            context.SaveChanges();

            // Document created as expected with _id for the Account document created.
            /*
            AccountData:
            {
                "_id" : LUUID("5331bdd2-ad9e-b547-acb0-b6eeec3253d9"),
                "Username" : "acc1796538846",
                "EmbeddedList" : [ 
                    {
                        "Name" : "asd",
                        "Foo" : 1001,
                        "Bar" : true
                    }, 
                    {
                        "Name" : "asd2",
                        "Foo" : 1002,
                        "Bar" : false
                    }, 
                    {
                        "Name" : "asd3",
                        "Foo" : 1003,
                        "Bar" : true
                    }
                ]
            }

        CharacterData:
            {
                "_id" : LUUID("b2a803f3-afbe-8145-b11e-38e1f4362ea0"),
                "Name" : "char1363200943",
                "Account" : {
                    "_id" : LUUID("5331bdd2-ad9e-b547-acb0-b6eeec3253d9")
                }
            }
                */

        }
                
        // Now trying to navigate to the AccountData from the CharacterData entity.
        using (var context = new FooContext())
        {
            var character = context.Characters.First();
            var account = character.Account;
            Console.WriteLine($"Test: {account.Id}");           // CORRECT (Guid)
            Console.WriteLine($"Test: {account.Username}");     // WRONG (Blank username)
            Console.WriteLine($"Test: {account.EmbededList}");  // WRONG (Empty list)
        }

    }
    catch (Exception ex)
    {
        throw ex;
    }

    Console.WriteLine("done!");
    Console.ReadLine();
}
```

**Comment by crhairr** [comment]
Try using `Include(character => character.Account)`.

**Comment by LoghamLogan** [comment]
Ah sorry, I did not realize that lazy loading is not yet implemented in EFCore yet!
Unfortunately, no luck using `Include(character => character.Account)` either.
Do I need to enable an option when configuring my context?

Looks like the model it's generating is correct:
```
Model: 
  EntityType: AccountData
    Properties: 
      Id (Guid) Required PK AfterSave:Throw ValueGenerated.OnAdd 0 0 0 -1 0
      EmbededList (ICollection<UserItem>) 1 1 -1 -1 -1
      Username (string) 2 2 -1 -1 -1
    Keys: 
      Id PK
    Annotations: 
      RelationshipDiscoveryConvention:NavigationCandidates: System.Collections.Immutable.ImmutableSortedDictionary`2[System.Reflection.PropertyInfo,System.Type]
  EntityType: CharacterData
    Properties: 
      Id (Guid) Required PK AfterSave:Throw ValueGenerated.OnAdd 0 0 0 -1 0
      AccountId (no field, Nullable<Guid>) Shadow FK Index 1 1 1 0 1
      Name (string) 2 2 -1 -1 -1
    Navigations: 
      Account (<Account>k__BackingField, AccountData) ToPrincipal AccountData 0 -1 2 -1 -1
    Keys: 
      Id PK
    Foreign keys: 
      CharacterData {'AccountId'} -> AccountData {'Id'} ToPrincipal: Account
    Annotations: 
      RelationshipDiscoveryConvention:NavigationCandidates: System.Collections.Immutable.ImmutableSortedDictionary`2[System.Reflection.PropertyInfo,System.Type]
Annotations: 
  MongoDb:Database: testdb
  ProductVersion: 2.1.0-preview1-27567
```

**Comment by crhairr** [comment]
I apologize for the delay: I was out of town over the weekend for the holiday. I'll be looking into this issue tonight when I get back to my personal PC.

In the meantime, take a look at [this unit test](https://github.com/crhairr/EntityFrameworkCore.MongoDb/blob/a465954e756865c771bed903b054d49acfe5db65/test/Blueshift.EntityFrameworkCore.MongoDB.Tests/MongoDbContextTests.cs#L119). See if there are any obvious differences between your data model and how I've set up the sample domain, as well as the use of the `Include` in the test.

**Comment by crhairr** [comment]
This should now be fixed. I was passing off my queries to the EF Core library for compilation, and it was making some assumptions about the underlying query provider that weren't holding up. Essentially, Includes get compiled to either Joins or GroupJoins with a transparent identifier, which EF Core executes client-side and then uses a projection to fix up the navigations. The metadata for EFCore-MongoDB didn't match what EF Core was expecting, so it was failing to fix up the navigations when processing the transparent identifiers. I had to completely rewrite the query compilation code for navigations in order to work around this, but it's now correctly using the $lookup operator.

Unfortunately, the current MongoDB C# driver does not yet have support for the $addFields or $mergeObjects pipeline operators (MongoDB 3.6+), so my code still has to use a transparent identifier and fix up the navigations once the results come back. This might cause unexpected behaviors in more complex queries (such as Including several layers of navigations, or including a navigation from a collection member, etc.) due to how the queries have to be rewritten in order for the transparent identifier to work. I have to explore these and make sure that the code handles them correctly, but for now simple navigation queries should load correctly.

[This single Include test](https://github.com/crhairr/EntityFrameworkCore.MongoDb/blob/49952539c65b482f248dcc5936405ea94b8ddc29/test/Blueshift.EntityFrameworkCore.MongoDB.Tests/MongoDbContextTests.cs#L144) and [this enumerable include test](https://github.com/crhairr/EntityFrameworkCore.MongoDb/blob/49952539c65b482f248dcc5936405ea94b8ddc29/test/Blueshift.EntityFrameworkCore.MongoDB.Tests/MongoDbContextTests.cs#L119) show navigations being loaded in a query, for reference.

Please give the latest preview build a try and let me know if you see any more issues.

**Comment by crhairr** [comment]
Tests are working: relationships are fully hydrated when using `Include`.
