### ISSUE TITLE
How to use relations with this?

### ISSUE THREAD

**Issue by mattwelke** [BlueshiftSoftware/EntityFrameworkCore#22]
I was testing this provider and tried using navigation properties to see how it stores related data. I wanted to see if it stored related documents as nested documents or used foreign keys using the ObjectIds. These are my models:

```csharp
// Models/Dog.cs

using System.ComponentModel.DataAnnotations;
using MongoDB.Bson;

namespace AspNetMvc.Models
{
    public class Dog
    {
        [Key]
        public ObjectId Id { get; set; }

        public string Breed { get; set; }

        public string Name { get; set; }

        //public Owner Owner { get; set; }
    }
}
```

```csharp
// Models/Owner.cs

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using MongoDB.Bson;

namespace AspNetMvc.Models
{
    public class Owner
    {
        [Key]
        public ObjectId Id { get; set; }

        public string Name { get; set; }

        public List<Dog> Dogs { get; set; } = new List<Dog>();
    }
}
```

The first problem I encountered was getting a StackOverflowException when attempting to use the navigation properties before commenting out `Dog`'s `Owner` property. It only worked when I had the navigation property on one side.

Then, when I used the following code to create the data:

```csharp
// Controllers/HomeController.cs

var borky = new Dog
{
    Breed = "Fluffer",
    Name = "Borky"
};

await _db.Dogs.AddAsync(borky);
await _db.SaveChangesAsync();

var newOwner = new Owner { Name = "Bob" };

await _db.Owners.AddAsync(newOwner);
await _db.SaveChangesAsync();

newOwner.Dogs.Add(borky);

await _db.SaveChangesAsync();
```

It ended up creating the "many" side (`Dog`) as a separate document without an `Owner` foreign key, and the `Owner` was created as a document with an array property called `Dogs` but it was empty. The data looked like this:

![](https://i.imgur.com/7v4gWfV.png)
![](https://i.imgur.com/U70zuTw.png)

Is there something wrong with the way I'm using relations here?

**Comment by mattwelke** [comment]
I ended up getting this working! I forgot to change the code back to something that made more sense while I was troubleshooting. When using EF Core properly with the relations, it worked fine, with the exception of the foreign key being stored as `ObjectId("000000000000000000000000")`.

![](https://i.imgur.com/5l3Yh2T.png)
![](https://i.imgur.com/zFcPToW.png)

I find the way the relationship is stored to be a bit concerning though. Since MongoDB has a 16 MB document limit, wouldn't a one-to-many relationship with *many* documents associated eventually exhaust this limit due to the array of foreign keys growing too large? Are there settings to change the foreign key ownership behavior?

**Comment by crhairr** [comment]
Well, this is definitely a bug. The way it's supposed to work is that `Dog` gets a transparent `OwnerId` and the $lookup uses that to hydrate the relationship. With the empty ObjectId, I'm not even sure how the relationship can be queried.

I'll take a look into this tonight. Are you doing anything with `OnModelCreating?`

**Comment by mattwelke** [comment]
Here is the complete code for the app I made to test this: https://gitlab.com/mattwelke/aspnetcore-mongo-efcore-test

I don't believe I touched OnModelCreating. I tried to keep it pretty simple.

**Comment by crhairr** [comment]
After looking through your project, one thing I'd note is to make sure that your `[Key]` properties are also annotated with `[DatabaseGenerated(DatabaseGeneratedOption.Identity)]` so that the identity gets assigned on insert. This might be why you're seeing the empty `ObjectId` in the DB.

**Comment by crhairr** [comment]
I apologize for not catching this earlier: `Dog` doesn't have an `Owner` property, so that subdocument isn't being generated on serialization. There's also no shadow `OwnerId` because EFCore-MongoDB is just a thin adapter between EFCore's Metadata system and the official MongoDB C# driver, which has no concept of relationships that aren't explicitly in the model.

I just hand off the documents to the driver and let it do the serialization (with minor modifications for denormalization, etc). If you add an `Owner` navigation property to `Dog`, it should serialize something like:

```js
{
    "owner": {
        "_id": ObjectId("...")
    }
}
```

Add the appropriate `[DatabaseGenerated]` annotation as well to ensure that ids are persisted on insert.

I probably need to beef up the [NavigationBsonSerializer](https://github.com/crhairr/EntityFrameworkCore.MongoDb/blob/develop/src/Blueshift.EntityFrameworkCore.MongoDB/Adapter/Serialization/NavigationBsonSerializer.cs) to make sure that it's not persisting both sides of the relationship, since the query system determines which side to use when performing a $lookup based on whether or not the navigation is mutual or one-sided. In this case, the query system should be doing a $lookup on `dogs.owner._id`, so serializing `owner.dogs._id` is superfluous.

**Comment by mattwelke** [comment]
I experienced a StackOverflowException when I had the `Dog` model have an `Owner` property. It didn't seem to like the navigation properties existing on both sides of the relation (which as far as I knew was idiomatic EF Core). Do you think that may have had something to do with serialization? I'd be happy to play around with it again with both navigation properties to try to recreate that exception and provide you with detailed logs showing what happens.

**Comment by crhairr** [comment]
Look at the sample  [ZooDbContext](https://github.com/crhairr/EntityFrameworkCore.MongoDb/blob/develop/src/Blueshift.EntityFrameworkCore.MongoDB.SampleDomain/ZooDbContext.cs):

[`Animal.Enclosure`](https://github.com/crhairr/EntityFrameworkCore.MongoDb/blob/e580ab6ac2844dee3da976a09391ee1ec8bbe9c6/src/Blueshift.EntityFrameworkCore.MongoDB.SampleDomain/ZooDbContext.cs#L66) <--> [`Enclosure.Animals`](https://github.com/crhairr/EntityFrameworkCore.MongoDb/blob/e580ab6ac2844dee3da976a09391ee1ec8bbe9c6/src/Blueshift.EntityFrameworkCore.MongoDB.SampleDomain/ZooDbContext.cs#L125)

I assure you, the integration tests explicitly exercise this mutual relationship, so I'm fairly confident that it works as expected.

**Comment by mattwelke** [comment]
Gotcha. It's definitely an issue with the way I set my test app up then. Once I fix this, the issue with the keys should resolve and so should my stack overflow. I'll comment back just to confirm anyways though. Thanks for your help and also thanks for this neat provider!

**Comment by crhairr** [comment]
Don't thank me until I publish the first actual release, now that EF Core 2.1 is official and stable and all that. ;)

I'll make sure to look into the dangling 1:M foreign keys before I publish. I'd hate for this to break on large collections, as you'd mentioned earlier.

**Comment by crhairr** [comment]
I apologize for the time it took to get back to this. The summer has been busy for me, and I haven't had a lot of free time.

I've updated the repo to use the mongo and mongo-express Docker images. This makes it much easier to get the repo up and running as well as viewing any files in the container during a test run.

I can't see any signs of any extra data being put in the DB for any particular relationship direction using the test domain.

If you are still seeing any strange data in your DB, please let me know and give me an example of your models that reproduces the problem. Otherwise, I just recommend looking into the test domain in this repo for an example on how to model your data.

I think I'll consider this closed for now.
