### ISSUE TITLE
Unable to install the package

### ISSUE THREAD

**Issue by godrose** [BlueshiftSoftware/EntityFrameworkCore#5]
Installing the latest preview (21.04.17) leads to compilation errors in my solution.

I'm using .net standard library 1.6 and EF 1.0.0

**Comment by crhairr** [comment]
@godrose EFCore-MongoDB is built against EF Core 2.0.0-preview* builds, and will not work with 1.x. There are older versions available that are compatible with EF Core 1.2.0-preview* build, but none for 1.x.

MongoDB requires complex type support, which is currently very limited in EF Core, and [is indefinitely backlogged by their team](https://github.com/aspnet/EntityFramework/issues/246). I have worked around the limitations, but [I made the decision](3) that until complex types are properly supported by the framework, EFCore-MongoDB will remain in beta/preview. Since there won't be an official release of EF Core 1.x with complex type support, it makes little sense to back-port a compatible preview version of EFCore-MongoDB.

**Comment by godrose** [comment]
I see. Will switch to the driver itself. Keep up the good work!

**Comment by crhairr** [comment]
Thanks, @godrose! I certainly don't want users to have to switch to the driver directly, since that's a lot of extra effort (especially if you want to use AspNet Core Identity). So, if I get some free time, I'll check out what it will take to create a 1.0.0 port of the repo. Also, any contributions along those lines are welcome!

I'll happily publish packages that are compatible with earlier versions of the framework, especially if anybody wants to pitch in on the code.

In the meantime, good luck with your project!

**Comment by crhairr** [comment]
[Duplicate of #3](3).
